docs: update example usage
mikehardy/buildcache-action pull request #110
Opened 2023-01-25 09:56 UTC by radko93

Currently example points to an old version. I would never find out that there is a new version if the old one would not use deprecated node version (also being used by checkout@v2).

2023-02-01 14:43 UTC, mikehardy requested changes
Oops! Good catch, thank you
I've made one suggestion which should help people access semver minors and patches, what do you think?

2023-02-01 14:43 UTC, mikehardy commented on README.md
> +    - uses: mikehardy/buildcache-action@v2.1.0
I slide the semver major tag up to match the current fully-specified version name, which means it is "safest" (as in: you will get bug fixes) to just use the semver major. This style appears to be semi-standard in the github action area, and is what github does, so should be a good suggestion...

```suggestion
    - uses: mikehardy/buildcache-action@v2
```

2023-02-01 14:43 UTC, mikehardy commented on README.md
> +  - uses: mikehardy/buildcache-action@v2.1.0
```suggestion
  - uses: mikehardy/buildcache-action@v2
```

2023-02-20 06:52 UTC, radko93 commented
Sorry, I had to test this but looks good, thanks for suggesting the changes!

2023-02-20 14:27 UTC, mikehardy approved these changes
💪 thank you!

2023-02-20 14:27 UTC, merged